spring.application.name=etl
spring.main.web-application-type=reactive
spring.r2dbc.url=r2dbc:h2:mem:///etldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
etl.source.base-url=https://jsonplaceholder.typicode.com
