CREATE TABLE IF NOT EXISTS records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id BIGINT,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    source VARCHAR(100) NOT NULL,
    CONSTRAINT uk_records_external_id UNIQUE (external_id)
);
